-- Copyright 2017 Google Inc.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

module Language.Kythe.Schema.Raw.VName
    ( VName(..)
    ) where

import Data.Text (Text)

-- | A VName (Vector-Name) is the primary unit of naming in the Kythe graph.
-- It is a set of basis facts about a graph node that can uniquely identify it.
data VName = VName
    { vnSignature :: !Text  -- ^ Opaque signature generated by an analyser.
    , vnCorpus    :: !Text  -- ^ Loosely, a collection of related files.
    , vnRoot      :: !Text  -- ^ Corpus-specific subtree root. Can be empty.
    , vnPath      :: !Text  -- ^ Location relative to the corpus and root.
    , vnLanguage  :: !Text  -- ^ Schema-defined label for supported languages.
    }
